name: Deploy Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy frontend to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 3.25.174.62
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "index.html"
        target: "/var/www/frontend"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 3.25.174.62
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx
